parameters:
#    msi_core.example.class: Msi\CoreBundle\Example

services:
#    msi_core.example:
#        class: %msi_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
